import type { Billboard, BillboardPhoto, EffectReport } from '@/types/database'

export const MOCK_PHOTOS: Record<string, BillboardPhoto[]> = {
  'bb-1': [
    { id: 'p1', billboard_id: 'bb-1', url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
    { id: 'p2', billboard_id: 'bb-1', url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop', photo_type: 'environment', is_primary: false, sort_order: 1, created_at: '' },
  ],
  'bb-2': [
    { id: 'p3', billboard_id: 'bb-2', url: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
  ],
  'bb-3': [
    { id: 'p4', billboard_id: 'bb-3', url: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
  ],
  'bb-4': [
    { id: 'p5', billboard_id: 'bb-4', url: 'https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
  ],
  'bb-5': [
    { id: 'p6', billboard_id: 'bb-5', url: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
  ],
  'bb-6': [
    { id: 'p7', billboard_id: 'bb-6', url: 'https://images.unsplash.com/photo-1496568816309-51d7c20e3b21?w=800&h=500&fit=crop', photo_type: 'front', is_primary: true, sort_order: 0, created_at: '' },
  ],
}

export const MOCK_BILLBOARDS: Billboard[] = [
  {
    id: 'bb-1',
    owner_id: 'owner-1',
    title: '忠孝東路四段 LED 電子牆',
    description: '位於忠孝敦化捷運站出口正上方，每日人流量超過 12 萬人次。24 小時全彩 LED，適合品牌形象廣告。',
    type: 'led',
    address: '台北市大安區忠孝東路四段 216 號',
    district: '大安區',
    city: '台北市',
    lat: 25.0418,
    lng: 121.5497,
    width_m: 12,
    height_m: 6,
    area_m2: 72,
    facing: 'S',
    has_lighting: true,
    is_digital: true,
    price_monthly: 180000,
    price_suggested: 165000,
    min_rental_months: 3,
    status: 'active',
    nearby_mrt: '忠孝敦化站',
    mrt_distance_m: 50,
    traffic_score: 95,
    foot_traffic_score: 92,
    visibility_score: 98,
    competition_density: 8,
    avg_effect_rating: 4.7,
    total_bookings: 23,
    created_at: '2025-08-15',
    updated_at: '2026-03-01',
    photos: MOCK_PHOTOS['bb-1'],
  },
  {
    id: 'bb-2',
    owner_id: 'owner-1',
    title: '信義計畫區松仁路大型看板',
    description: '面對 101 大樓方向，車流量大，週末人潮集中。適合精品、汽車等高端品牌。',
    type: 'wall',
    address: '台北市信義區松仁路 89 號',
    district: '信義區',
    city: '台北市',
    lat: 25.0330,
    lng: 121.5654,
    width_m: 15,
    height_m: 8,
    area_m2: 120,
    facing: 'W',
    has_lighting: true,
    is_digital: false,
    price_monthly: 250000,
    price_suggested: 240000,
    min_rental_months: 6,
    status: 'active',
    nearby_mrt: '象山站',
    mrt_distance_m: 300,
    traffic_score: 88,
    foot_traffic_score: 85,
    visibility_score: 90,
    competition_density: 12,
    avg_effect_rating: 4.5,
    total_bookings: 15,
    created_at: '2025-06-20',
    updated_at: '2026-02-10',
    photos: MOCK_PHOTOS['bb-2'],
  },
  {
    id: 'bb-3',
    owner_id: 'owner-2',
    title: '南京復興站 T 霸',
    description: '南京東路與復興北路交叉口，雙向車流皆可見。高度 15 公尺，遠距離可視性極佳。',
    type: 'pole',
    address: '台北市中山區南京東路三段 1 號',
    district: '中山區',
    city: '台北市',
    lat: 25.0522,
    lng: 121.5445,
    width_m: 10,
    height_m: 5,
    area_m2: 50,
    facing: 'E',
    has_lighting: true,
    is_digital: false,
    price_monthly: 95000,
    price_suggested: 90000,
    min_rental_months: 3,
    status: 'active',
    nearby_mrt: '南京復興站',
    mrt_distance_m: 80,
    traffic_score: 82,
    foot_traffic_score: 78,
    visibility_score: 85,
    competition_density: 6,
    avg_effect_rating: 4.2,
    total_bookings: 31,
    created_at: '2025-03-10',
    updated_at: '2026-01-20',
    photos: MOCK_PHOTOS['bb-3'],
  },
  {
    id: 'bb-4',
    owner_id: 'owner-2',
    title: '西門町中華路圍牆廣告',
    description: '西門町徒步區入口旁，年輕族群聚集地。適合潮牌、演唱會、電影宣傳。',
    type: 'fence',
    address: '台北市萬華區中華路一段 120 號',
    district: '萬華區',
    city: '台北市',
    lat: 25.0422,
    lng: 121.5069,
    width_m: 20,
    height_m: 3,
    area_m2: 60,
    facing: 'N',
    has_lighting: true,
    is_digital: false,
    price_monthly: 55000,
    price_suggested: 50000,
    min_rental_months: 1,
    status: 'active',
    nearby_mrt: '西門站',
    mrt_distance_m: 120,
    traffic_score: 75,
    foot_traffic_score: 95,
    visibility_score: 80,
    competition_density: 15,
    avg_effect_rating: 4.0,
    total_bookings: 42,
    created_at: '2025-01-05',
    updated_at: '2026-03-15',
    photos: MOCK_PHOTOS['bb-4'],
  },
  {
    id: 'bb-5',
    owner_id: 'owner-3',
    title: '內湖科技園區屋頂看板',
    description: '內湖科技園區核心位置，面對環東大道。每日通勤車流量極大，上班族精準觸及。',
    type: 'rooftop',
    address: '台北市內湖區瑞光路 513 巷',
    district: '內湖區',
    city: '台北市',
    lat: 25.0780,
    lng: 121.5755,
    width_m: 18,
    height_m: 6,
    area_m2: 108,
    facing: 'SW',
    has_lighting: false,
    is_digital: false,
    price_monthly: 72000,
    price_suggested: 68000,
    min_rental_months: 6,
    status: 'active',
    nearby_mrt: '港墘站',
    mrt_distance_m: 450,
    traffic_score: 78,
    foot_traffic_score: 45,
    visibility_score: 75,
    competition_density: 3,
    avg_effect_rating: 3.8,
    total_bookings: 8,
    created_at: '2025-09-01',
    updated_at: '2026-02-28',
    photos: MOCK_PHOTOS['bb-5'],
  },
  {
    id: 'bb-6',
    owner_id: 'owner-3',
    title: '士林夜市文林路跨橋看板',
    description: '文林路跨越基隆河橋樑側面，雙向車流。夜市人潮加持，夜間曝光量特別高。',
    type: 'bridge',
    address: '台北市士林區文林路 101 號',
    district: '士林區',
    city: '台北市',
    lat: 25.0880,
    lng: 121.5240,
    width_m: 14,
    height_m: 4,
    area_m2: 56,
    facing: 'SE',
    has_lighting: true,
    is_digital: false,
    price_monthly: 48000,
    price_suggested: 45000,
    min_rental_months: 3,
    status: 'active',
    nearby_mrt: '劍潭站',
    mrt_distance_m: 200,
    traffic_score: 70,
    foot_traffic_score: 88,
    visibility_score: 72,
    competition_density: 5,
    avg_effect_rating: 4.1,
    total_bookings: 19,
    created_at: '2025-05-12',
    updated_at: '2026-03-10',
    photos: MOCK_PHOTOS['bb-6'],
  },
]

export const MOCK_EFFECTS: EffectReport[] = [
  {
    id: 'eff-1',
    booking_id: 'bk-1',
    billboard_id: 'bb-1',
    advertiser_id: 'adv-1',
    visibility_rating: 5,
    location_rating: 5,
    value_rating: 4,
    overall_rating: 5,
    ad_goal: '品牌知名度提升',
    perceived_reach: '高',
    would_rebook: true,
    estimated_leads_increase: '30%',
    public_comment: '忠孝東路的人流真的非常驚人，品牌曝光效果超出預期。LED 畫質清晰，夜間效果尤其好。',
    private_note: null,
    created_at: '2026-02-15',
  },
  {
    id: 'eff-2',
    booking_id: 'bk-2',
    billboard_id: 'bb-1',
    advertiser_id: 'adv-2',
    visibility_rating: 5,
    location_rating: 4,
    value_rating: 4,
    overall_rating: 4,
    ad_goal: '新品上市宣傳',
    perceived_reach: '中高',
    would_rebook: true,
    estimated_leads_increase: '20%',
    public_comment: '捷運站出口的位置很棒，上下班時段幾乎每個人都會看到。',
    private_note: null,
    created_at: '2026-01-20',
  },
  {
    id: 'eff-3',
    booking_id: 'bk-3',
    billboard_id: 'bb-2',
    advertiser_id: 'adv-1',
    visibility_rating: 4,
    location_rating: 5,
    value_rating: 3,
    overall_rating: 4,
    ad_goal: '高端品牌定位',
    perceived_reach: '中',
    would_rebook: true,
    estimated_leads_increase: '15%',
    public_comment: '信義區的環境很適合精品品牌，看板維護狀態也很好。價格偏高但值得。',
    private_note: null,
    created_at: '2025-12-05',
  },
]

export function getMockBillboard(id: string): Billboard | undefined {
  return MOCK_BILLBOARDS.find((b) => b.id === id)
}

export function getMockEffects(billboardId: string): EffectReport[] {
  return MOCK_EFFECTS.filter((e) => e.billboard_id === billboardId)
}
